# FIle: test.yml
# Author: aeternus <aeternus@aliyun.com>
# Date: 2019-12-26
# Description:
#   Test Ansible role

name: Test

on:
  push:
    branches:
      - master

jobs:
  test:

    name: Test Ansible Role
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: "2.7"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          ansible --version

      - name: Run Test
        run: |
          # Create ansible.cfg with correct roles_path
          printf '[defaults]\nroles_path=../' >ansible.cfg
          # Basic role syntax check
          ansible-playbook tests/test.yml -i tests/inventory --syntax-check
